backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "images/uploads"

collections:
  - name: "wiki"
    label: "Wiki"
    folder: "content/lessons"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}